export enum tagTypes {
	user = "user",
	user_details = "user_details",
	category = "category",
	categoryDetails = "category_details",
	file = "file",
	service = "service",
	service_details = "service_details",
	service_by_category = "service_by_category",
	worker = "worker",
	worker_details = "worker_details",
	schedule = "schedule",
	schedule_details = "schedule_details",
	appointment = "appointment",
	appointment_details = "appointment_details",
	blog = "blog",
	blog_by_service = "blog_by_service",
	blog_details = "blog_details",
	review = "review",
	review_details = "review_details",
	user_profile = "user_profile",
}

export const tagTypesList = [
	tagTypes.user,
	tagTypes.user_details,
	tagTypes.category,
	tagTypes.categoryDetails,
	tagTypes.file,
	tagTypes.service_details,
	tagTypes.service_by_category,
	tagTypes.worker,
	tagTypes.worker_details,
	tagTypes.schedule,
	tagTypes.schedule_details,
	tagTypes.appointment,
	tagTypes.appointment_details,
	tagTypes.blog,
	tagTypes.blog_details,
	tagTypes.blog_by_service,
	tagTypes.review,
	tagTypes.review_details,
	tagTypes.user_profile,
];

